spring.application.name=azentio

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/azentio
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080